add working ci pipeline

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,4 +1,4 @@
-name: My first pipeline
+name: CI/CD Pipeline
 
 on:
   push:
@@ -10,13 +10,13 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      - name: checkout code
+      - name: Checkout code
         uses: actions/checkout@v4
 
-      - name: Build image
+      - name: Build Docker image
         run: |
           docker build -t ${{ secrets.DOCKER_USERNAME }}/portfolio-app:${{ github.run_number }} .
-          docker build -t ${{ secrets.DOCKER_USERNAME }}/portfolio-app .
+          docker build -t ${{ secrets.DOCKER_USERNAME }}/portfolio-app:latest .
 
       - name: Docker login
         uses: docker/login-action@v2
@@ -27,4 +27,21 @@ jobs:
       - name: Push image to registry
         run: |
           docker push ${{ secrets.DOCKER_USERNAME }}/portfolio-app:${{ github.run_number }}
-          docker push ${{ secrets.DOCKER_USERNAME }}/portfolio-app
+          docker push ${{ secrets.DOCKER_USERNAME }}/portfolio-app:latest
+
+  deploy:
+    needs: build
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: SSH to Linux and run container
+        uses: appleboy/ssh-action@v1
+        with:
+          host: ${{ secrets.HOST }}
+          username: ${{ secrets.SSH_USERNAME }}
+          key: ${{ secrets.PRIVATE_KEY }}
+          port: ${{ secrets.PORT }}
+          script: |
+            docker rm -f portfolio || echo "Container not found, skipping removal."
+            docker pull ${{ secrets.DOCKER_USERNAME }}/portfolio-app:latest
+            docker run -d --name portfolio -p 8080:80 ${{ secrets.DOCKER_USERNAME }}/portfolio-app:latest
